Repository googleapis/nodejs-document-ai, pull requests merged in 2020-10, with the labels that each got.

#102 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#104 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: automerge: exact, cla: yes, context: full

#112 feat: generation error and set v1beta2 as default
  .jsdoc.js
  samples/batch_parse_form.js
  samples/batch_parse_table.js
  samples/parse_form.js
  samples/parse_table.js
  samples/parse_with_model.js
  samples/quickstart.js
  samples/set_endpoint.js
  src/index.ts
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
Labels: cla: yes

#115 chore: update packageName and README
  .jsdoc.js
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: partial

#117 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#118 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#121 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: automerge, cla: yes, context: full
