Repository googleapis/nodejs-document-ai, pull requests merged in 2020-12, with the labels that each got.

#138 docs: update README to reflect corrected variable name
  README.md
  synth.metadata
Labels: cla: yes, context: none

#136 docs: make processor ID variable consistent with comments in snippet
  samples/process-document.v1beta3.js
Labels: cla: yes

#139 chore: generate GAPIC metadata JSON file
  src/v1beta2/gapic_metadata.json
  src/v1beta3/gapic_metadata.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#140 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
