Repository googleapis/nodejs-document-ai, pull requests merged in 2020-11, with the labels that each got.

#122 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#123 chore: fix namespaces for ruby, php, and C# clients, add package name for v1beta3
  protos/google/cloud/documentai/v1beta2/document.proto
  protos/google/cloud/documentai/v1beta2/document_understanding.proto
  protos/google/cloud/documentai/v1beta2/geometry.proto
  protos/google/cloud/documentai/v1beta3/document.proto
  protos/google/cloud/documentai/v1beta3/document_processor_service.proto
  protos/google/cloud/documentai/v1beta3/geometry.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: partial

#124 build: add DocumentProcessorServiceClient type
  src/index.ts
  synth.metadata
Labels: cla: yes, context: none

#125 fix: do not modify options object, use defaultScopes
  package.json
  src/v1beta2/document_understanding_service_client.ts
  src/v1beta3/document_processor_service_client.ts
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: cla: yes

#131 fix(browser): check for fetch on window
  protos/protos.json
  src/v1beta2/document_understanding_service_client.ts
  src/v1beta3/document_processor_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#133 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#137 docs: make projectId variable consistent in quickstart.js comments
  samples/quickstart.js
Labels: cla: yes
