Repository googleapis/nodejs-document-ai, pull requests merged in 2021-02, with the labels that each got.

#149 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: automerge, cla: yes

#150 build: adds UNORDERED_LIST enum
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#152 feat: Update documentai/v1beta3 protos
  protos/google/cloud/documentai/v1beta3/document_io.proto
  protos/google/cloud/documentai/v1beta3/document_processor_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1beta3/document_processor_service_client.ts
  src/v1beta3/document_processor_service_proto_list.json
  synth.metadata
Labels: cla: yes, context: full

#154 feat: Update documentai/v1beta3 protos: add support for boolean normalized value
  protos/google/cloud/documentai/v1beta3/document.proto
  protos/google/cloud/documentai/v1beta3/document_io.proto
  protos/google/cloud/documentai/v1beta3/geometry.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: documentai, cla: yes, context: full
