Repository googleapis/nodejs-document-ai, pull requests merged in 2021-03, with the labels that each got.

#156 build: add OwlBot configuration
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: api: documentai, cla: yes

#157 build: fix OwlBot.yaml config format
  .github/.OwlBot.yaml
Labels: api: documentai, cla: yes

#159 build: proto copy path was incorrect
  .github/.OwlBot.yaml
  src/index.ts
Labels: api: documentai, cla: yes

#164 build: update copyright
  synth.metadata
  webpack.config.js
Labels: api: documentai, cla: yes, context: partial

#181 feat: remove the translation fields in document.proto
  protos/google/cloud/documentai/v1beta3/document.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: documentai, cla: yes, context: partial

#183 build: update metadata
  synth.metadata
Labels: api: documentai, cla: yes, context: none

#184 build: update synthtool sha
  synth.metadata
Labels: api: documentai, cla: yes, context: none
