Repository googleapis/nodejs-document-ai, pull requests merged in 2021-01, with the labels that each got.

#142 docs: update dates
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v1beta2/document_understanding_service_client.ts
  src/v1beta2/index.ts
  src/v1beta3/document_processor_service_client.ts
  src/v1beta3/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_document_processor_service_v1beta3.ts
  test/gapic_document_understanding_service_v1beta2.ts
Labels: cla: yes, context: none

#143 feat: adds style enumeration
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#146 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 build: update package name
  .repo-metadata.json
Labels: cla: yes
