Repository googleapis/nodejs-document-ai, pull requests merged in 2021-04, with the labels that each got.

#190 build: update sha
  synth.metadata
Labels: api: documentai, cla: yes, context: none

#192 build: fix OwlBot configuration
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  owlbot.py
  src/index.ts
  synth.py
Labels: api: documentai, cla: yes

#191 feat: add EVAL_SKIPPED value to the Provenance.OperationType enum
  protos/google/cloud/documentai/v1beta3/document.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: documentai, cla: yes, context: partial
